### ISSUE TITLE
[Bug]:  2A3A1-AMPCD.ino backlighting and controls become unresponsive

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet-Software#104]
### Discord Username

Arribe

### Bug Summary

The backlighting doesn't work.

The controls become unresponsive at random times, requiring a full power off and disconnect of the pro micro to make it work again.

### Expected Results

backlighting works, and controls do not become unresponsive.

### Actual Results

no backlighting and controls become unresponsive.

### Applicable File Names

2A3A1-AMPCD.ino

### Release Version

v0.3.0

### Category

embedded (Arduino Sketches/Microcontroller embedded software)

### Applicable End Item(s)

Lower Instrument Panel (LIP)

### Hardware is built to print & this software is tested on that hardware?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations and tested the software on it.
- [X] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

I have the fix.

**Comment by jrsteensen** [comment]
Thanks @Arribe for the bug stomp!
