### ISSUE TITLE
[Bug]: L and R DDI, backlighting and control unresponsiveness

### ISSUE THREAD

**Issue by Arribe** [jrsteensen/OpenHornet-Software#106]
### Discord Username

Arribe

### Bug Summary

Same issue as bug #104:  Controls randomly become unresponsive.

### Expected Results

Backlighting and controls remain responsive

### Actual Results

controls will become unresponsive at random times, leading to needing to remove power and disconnect from USB to restore the button interactions with DCS Bios.

### Applicable File Names

1A9-R_DDI_AND_EWI.ino, 1A3-L_DDI_AND_EWI.ino

### Release Version

v0.3.0

### Category

embedded (Arduino Sketches/Microcontroller embedded software)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Hardware is built to print & this software is tested on that hardware?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations and tested the software on it.
- [X] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

I have the fix.

**Comment by jrsteensen** [comment]
Closed with #107
