### ISSUE TITLE
[FEATURE REQUEST]: Standardize DCS-BIOS Versions and Recommended Tools for DCS-BIOS Developement

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet-Software#17]
### Discord Username

smgvbest (aka Sandra)

### Feature/Enhancement Summary

To give everyone doing OH Development a baseline for working with DCS-BIOS and to provide some recommended tools and their version,   we should standardize on minimum levels of the following

dcs-bios-arduino-library-0.3.9 or greater
DCS-BIOS v2.8.7 or greater 

Tools to aid in DCS-BIOS Development (not needed to compile)
Bort v0.2.4 or greater
Dcs-Insight v1.8.3 or greater

### Actual Results

N/A in this case

### Applicable File Names

ALL Firmware/Libraries using DCS-BIOS

### Release Version

1.0.0-beta.2

### Category

Libraries & Dependencies (Arduino Libraries, etc), DCS-BIOS, Documentation

### Applicable End Item(s)

Top Level Assembly (TLA), Upper Instrument Panel (UIP), Lower Instrument Panel (LIP), Center Tub (CT), Left Console (LCON), Right Console (RCON), Flight Stick, Throttle

### Hardware is built to print & this software is tested on that hardware?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations and tested the software on it.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

### Miscellaneous Info

Nothing to add

**Comment by jrsteensen** [comment]
Added to SoftwareManual.md in #16. 

```
- Arduino IDE (with Libraries listed below)
- GNU Make
- Local Doxygen installation
- OpenHornetSandbox access

## Supported Software

- Arduino 1.8.10
- GNU Make 3.81+
- DCS-BIOS v2.8.7+
- Doxygen 1.8.13

### Arduino Libraries

- dcs-bios-arduino-library-0.3.9+

### Suggested debug tools

- Bort v0.2.4+
- Dcs-Insight v1.8.3+
```
